version: '3'

services:
  craftcms:
    image: burnett01/docker-craftcms
    ports:
      - "80:80"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./public:/var/www/html
      - ./compose/config:/etc/apache2/sites-enabled:rw
      - ./compose/logs:/var/log/apache2:rw
    tty: true

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_pw
      MYSQL_USER: acme
      MYSQL_PASSWORD: acme
      MYSQL_DATABASE: acmedb
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: mysqld --sql_mode=""

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
